// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"
	"time"

	"github.com/mk6i/open-oscar-server/state"
	mock "github.com/stretchr/testify/mock"
)

// newMockE2EDeviceManager creates a new instance of mockE2EDeviceManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockE2EDeviceManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockE2EDeviceManager {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockE2EDeviceManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockE2EDeviceManager is an autogenerated mock type for the E2EDeviceManager type
type mockE2EDeviceManager struct {
	mock.Mock
}

type mockE2EDeviceManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockE2EDeviceManager) EXPECT() *mockE2EDeviceManager_Expecter {
	return &mockE2EDeviceManager_Expecter{mock: &_m.Mock}
}

// E2EAccount provides a mock function for the type mockE2EDeviceManager
func (_mock *mockE2EDeviceManager) E2EAccount(ctx context.Context, screenName state.IdentScreenName) (*state.E2EAccount, error) {
	ret := _mock.Called(ctx, screenName)

	if len(ret) == 0 {
		panic("no return value specified for E2EAccount")
	}

	var r0 *state.E2EAccount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) (*state.E2EAccount, error)); ok {
		return returnFunc(ctx, screenName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) *state.E2EAccount); ok {
		r0 = returnFunc(ctx, screenName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*state.E2EAccount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.IdentScreenName) error); ok {
		r1 = returnFunc(ctx, screenName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockE2EDeviceManager_E2EAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'E2EAccount'
type mockE2EDeviceManager_E2EAccount_Call struct {
	*mock.Call
}

// E2EAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
func (_e *mockE2EDeviceManager_Expecter) E2EAccount(ctx any, screenName any) *mockE2EDeviceManager_E2EAccount_Call {
	return &mockE2EDeviceManager_E2EAccount_Call{Call: _e.mock.On("E2EAccount", ctx, screenName)}
}

func (_c *mockE2EDeviceManager_E2EAccount_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName)) *mockE2EDeviceManager_E2EAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockE2EDeviceManager_E2EAccount_Call) Return(e2EAccount *state.E2EAccount, err error) *mockE2EDeviceManager_E2EAccount_Call {
	_c.Call.Return(e2EAccount, err)
	return _c
}

func (_c *mockE2EDeviceManager_E2EAccount_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName) (*state.E2EAccount, error)) *mockE2EDeviceManager_E2EAccount_Call {
	_c.Call.Return(run)
	return _c
}

// E2EDevices provides a mock function for the type mockE2EDeviceManager
func (_mock *mockE2EDeviceManager) E2EDevices(ctx context.Context, screenName state.IdentScreenName) ([]state.E2EDevice, error) {
	ret := _mock.Called(ctx, screenName)

	if len(ret) == 0 {
		panic("no return value specified for E2EDevices")
	}

	var r0 []state.E2EDevice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) ([]state.E2EDevice, error)); ok {
		return returnFunc(ctx, screenName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) []state.E2EDevice); ok {
		r0 = returnFunc(ctx, screenName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]state.E2EDevice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.IdentScreenName) error); ok {
		r1 = returnFunc(ctx, screenName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockE2EDeviceManager_E2EDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'E2EDevices'
type mockE2EDeviceManager_E2EDevices_Call struct {
	*mock.Call
}

// E2EDevices is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
func (_e *mockE2EDeviceManager_Expecter) E2EDevices(ctx any, screenName any) *mockE2EDeviceManager_E2EDevices_Call {
	return &mockE2EDeviceManager_E2EDevices_Call{Call: _e.mock.On("E2EDevices", ctx, screenName)}
}

func (_c *mockE2EDeviceManager_E2EDevices_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName)) *mockE2EDeviceManager_E2EDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockE2EDeviceManager_E2EDevices_Call) Return(e2EDevices []state.E2EDevice, err error) *mockE2EDeviceManager_E2EDevices_Call {
	_c.Call.Return(e2EDevices, err)
	return _c
}

func (_c *mockE2EDeviceManager_E2EDevices_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName) ([]state.E2EDevice, error)) *mockE2EDeviceManager_E2EDevices_Call {
	_c.Call.Return(run)
	return _c
}

// E2ERevokeDevice provides a mock function for the type mockE2EDeviceManager
func (_mock *mockE2EDeviceManager) E2ERevokeDevice(ctx context.Context, screenName state.IdentScreenName, deviceID uint32, by state.E2EAuthority, now time.Time) error {
	ret := _mock.Called(ctx, screenName, deviceID, by, now)

	if len(ret) == 0 {
		panic("no return value specified for E2ERevokeDevice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, uint32, state.E2EAuthority, time.Time) error); ok {
		r0 = returnFunc(ctx, screenName, deviceID, by, now)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockE2EDeviceManager_E2ERevokeDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'E2ERevokeDevice'
type mockE2EDeviceManager_E2ERevokeDevice_Call struct {
	*mock.Call
}

// E2ERevokeDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
//   - deviceID uint32
//   - by state.E2EAuthority
//   - now time.Time
func (_e *mockE2EDeviceManager_Expecter) E2ERevokeDevice(ctx any, screenName any, deviceID any, by any, now any) *mockE2EDeviceManager_E2ERevokeDevice_Call {
	return &mockE2EDeviceManager_E2ERevokeDevice_Call{Call: _e.mock.On("E2ERevokeDevice", ctx, screenName, deviceID, by, now)}
}

func (_c *mockE2EDeviceManager_E2ERevokeDevice_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName, deviceID uint32, by state.E2EAuthority, now time.Time)) *mockE2EDeviceManager_E2ERevokeDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		var arg2 uint32
		if args[2] != nil {
			arg2 = args[2].(uint32)
		}
		var arg3 state.E2EAuthority
		if args[3] != nil {
			arg3 = args[3].(state.E2EAuthority)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *mockE2EDeviceManager_E2ERevokeDevice_Call) Return(err error) *mockE2EDeviceManager_E2ERevokeDevice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockE2EDeviceManager_E2ERevokeDevice_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName, deviceID uint32, by state.E2EAuthority, now time.Time) error) *mockE2EDeviceManager_E2ERevokeDevice_Call {
	_c.Call.Return(run)
	return _c
}
